"""Permission catalog and default role grants.

Permissions are `module.feature.action` strings (per the platform brief's
§34 shape) stored as data in the `permissions` table, not a code enum - new
modules add rows here as they land in later phases (FR-PLT-009: master data
is shared platform config, not per-feature hardcoding). Roles mirror the
persona list in 01-VISION.md §4.
"""

PERMISSIONS: list[tuple[str, str]] = [
    ("platform.tenant.create", "Create a new tenant (platform super admin only in practice)"),
    ("platform.user.manage", "Create/update users within the tenant"),
    ("platform.role.assign", "Assign roles/scopes to users"),
    ("platform.audit.view", "View the audit trail"),
    ("platform.config.manage", "Read/write tenant configuration"),
    ("master_data.crop.view", "View crop/variety master data"),
    ("master_data.crop.manage", "Create/update crop/variety master data"),
    ("farm.view", "View farm/zone/plot/block/row hierarchy"),
    ("farm.manage", "Create/update farm/zone/plot/block/row hierarchy"),
    ("tree.view", "View tree twins and their history"),
    ("tree.manage", "Create/update/delete tree twins"),
    ("tree.event.record", "Record a tree history event (health/irrigation/treatment/harvest/...)"),
    ("season.view", "View seasons"),
    ("season.manage", "Create/update seasons"),
    ("twin.view", "View digital twins, their properties, events, and telemetry"),
    ("twin.manage", "Create/update/delete digital twins, their relationships, properties, and events"),
    ("twin.telemetry.write", "Record telemetry readings against a digital twin"),
    ("iot.device.view", "View IoT device/gateway registrations"),
    ("iot.device.manage", "Register/update IoT devices and gateways"),
    ("iot.rule.view", "View IoT threshold rules"),
    ("iot.rule.manage", "Create/update IoT threshold rules"),
    ("alert.view", "View alerts"),
    ("alert.manage", "Acknowledge/resolve alerts"),
    ("irrigation.plan.view", "View irrigation plans and events"),
    ("irrigation.plan.manage", "Create/submit/execute irrigation plans"),
    ("fertigation.plan.view", "View fertigation plans and events"),
    ("fertigation.plan.manage", "Create/submit/execute fertigation plans"),
    ("fertilizer.view", "View fertilizer master data"),
    ("fertilizer.manage", "Create/update fertilizer master data"),
    ("weather.view", "View weather readings"),
    ("weather.ingest", "Ingest station/forecast weather readings"),
    ("vision.camera.view", "View camera registrations"),
    ("vision.camera.manage", "Register/update cameras"),
    ("vision.model.view", "View the vision model catalog"),
    ("vision.model.manage", "Create/update vision model catalog entries"),
    ("vision.detection.view", "View vision AI detections"),
    ("vision.detection.manage", "Create detections and confirm/reject them"),
    ("crophealth.disease.view", "View the disease/pest master catalog"),
    ("crophealth.disease.manage", "Create/update the disease/pest master catalog"),
    ("crophealth.incident.view", "View disease incidents and disease-risk signals"),
    ("crophealth.incident.manage", "Create disease incidents and change their lifecycle status"),
    ("crophealth.treatment.view", "View treatment plans and events"),
    ("crophealth.treatment.manage", "Create/submit/execute treatment plans"),
    ("harvest.observation.view", "View fruit lifecycle observations"),
    ("harvest.observation.manage", "Record fruit lifecycle observations"),
    ("harvest.yield.view", "View yield forecasts"),
    ("harvest.yield.manage", "Create yield forecasts"),
    ("harvest.lot.view", "View harvest lots and packing lots"),
    ("harvest.lot.manage", "Create harvest lots and packing lots"),
    ("workflow.definition.manage", "Create/update approval workflow definitions"),
    ("workflow.instance.submit", "Submit an entity for approval"),
    ("workflow.instance.approve", "Approve/reject/return a submitted workflow instance"),
    ("notification.view", "View own notifications"),
]

SYSTEM_ROLES: list[tuple[str, str]] = [
    ("tenant_admin", "Tenant Admin"),
    ("farm_owner", "Farm Owner"),
    ("farm_manager", "Farm Manager"),
    ("agronomist", "Agronomist"),
    ("field_worker", "Field Worker"),
    ("maintenance_engineer", "Maintenance Engineer"),
    ("warehouse_officer", "Warehouse / Procurement Officer"),
    ("finance", "Finance / Cost Controller"),
    ("auditor", "Auditor"),
    ("viewer", "Viewer"),
]

DEFAULT_ROLE_PERMISSIONS: dict[str, list[str]] = {
    "tenant_admin": [code for code, _ in PERMISSIONS],
    "farm_owner": [
        "platform.audit.view",
        "master_data.crop.view",
        "farm.view",
        "farm.manage",
        "tree.view",
        "tree.manage",
        "season.view",
        "season.manage",
        "twin.view",
        "twin.manage",
        "iot.device.view",
        "iot.device.manage",
        "iot.rule.view",
        "iot.rule.manage",
        "alert.view",
        "alert.manage",
        "irrigation.plan.view",
        "irrigation.plan.manage",
        "fertigation.plan.view",
        "fertigation.plan.manage",
        "fertilizer.view",
        "fertilizer.manage",
        "weather.view",
        "weather.ingest",
        "vision.camera.view",
        "vision.camera.manage",
        "vision.model.view",
        "vision.model.manage",
        "vision.detection.view",
        "vision.detection.manage",
        "crophealth.disease.view",
        "crophealth.disease.manage",
        "crophealth.incident.view",
        "crophealth.incident.manage",
        "crophealth.treatment.view",
        "crophealth.treatment.manage",
        "harvest.observation.view",
        "harvest.observation.manage",
        "harvest.yield.view",
        "harvest.yield.manage",
        "harvest.lot.view",
        "harvest.lot.manage",
        "workflow.instance.approve",
        "notification.view",
    ],
    "farm_manager": [
        "master_data.crop.view",
        "farm.view",
        "farm.manage",
        "tree.view",
        "tree.manage",
        "tree.event.record",
        "season.view",
        "season.manage",
        "twin.view",
        "twin.manage",
        "twin.telemetry.write",
        "iot.device.view",
        "iot.device.manage",
        "iot.rule.view",
        "iot.rule.manage",
        "alert.view",
        "alert.manage",
        "irrigation.plan.view",
        "irrigation.plan.manage",
        "fertigation.plan.view",
        "fertigation.plan.manage",
        "fertilizer.view",
        "fertilizer.manage",
        "weather.view",
        "weather.ingest",
        "vision.camera.view",
        "vision.camera.manage",
        "vision.model.view",
        "vision.model.manage",
        "vision.detection.view",
        "vision.detection.manage",
        "crophealth.disease.view",
        "crophealth.disease.manage",
        "crophealth.incident.view",
        "crophealth.incident.manage",
        "crophealth.treatment.view",
        "crophealth.treatment.manage",
        "harvest.observation.view",
        "harvest.observation.manage",
        "harvest.yield.view",
        "harvest.yield.manage",
        "harvest.lot.view",
        "harvest.lot.manage",
        "workflow.instance.submit",
        "workflow.instance.approve",
        "notification.view",
    ],
    "agronomist": [
        "master_data.crop.view",
        "farm.view",
        "tree.view",
        "tree.manage",
        "tree.event.record",
        "season.view",
        "twin.view",
        "iot.device.view",
        "iot.rule.view",
        "alert.view",
        "irrigation.plan.view",
        "irrigation.plan.manage",
        "fertigation.plan.view",
        "fertigation.plan.manage",
        "fertilizer.view",
        "weather.view",
        "vision.camera.view",
        "vision.model.view",
        "vision.detection.view",
        "vision.detection.manage",
        "crophealth.disease.view",
        "crophealth.incident.view",
        "crophealth.incident.manage",
        "crophealth.treatment.view",
        "crophealth.treatment.manage",
        "harvest.observation.view",
        "harvest.observation.manage",
        "harvest.yield.view",
        "harvest.yield.manage",
        "harvest.lot.view",
        "harvest.lot.manage",
        "workflow.instance.submit",
        "notification.view",
    ],
    "field_worker": [
        "farm.view",
        "tree.view",
        "tree.event.record",
        "twin.view",
        "iot.device.view",
        "alert.view",
        "alert.manage",
        "irrigation.plan.view",
        "irrigation.plan.manage",
        "fertigation.plan.view",
        "fertigation.plan.manage",
        "fertilizer.view",
        "weather.view",
        "weather.ingest",
        "vision.camera.view",
        "vision.detection.view",
        "vision.detection.manage",
        "crophealth.disease.view",
        "crophealth.incident.view",
        "crophealth.treatment.view",
        "crophealth.treatment.manage",
        "harvest.observation.view",
        "harvest.observation.manage",
        "harvest.yield.view",
        "harvest.lot.view",
        "harvest.lot.manage",
        "notification.view",
    ],
    "maintenance_engineer": [
        "twin.view",
        "twin.manage",
        "twin.telemetry.write",
        "iot.device.view",
        "iot.device.manage",
        "iot.rule.view",
        "iot.rule.manage",
        "alert.view",
        "alert.manage",
        "workflow.instance.submit",
        "notification.view",
    ],
    "warehouse_officer": [
        "workflow.instance.submit",
        "notification.view",
    ],
    "finance": [
        "workflow.instance.approve",
        "platform.audit.view",
        "notification.view",
    ],
    "auditor": ["platform.audit.view", "notification.view"],
    "viewer": [
        "master_data.crop.view",
        "farm.view",
        "tree.view",
        "season.view",
        "twin.view",
        "iot.device.view",
        "iot.rule.view",
        "alert.view",
        "irrigation.plan.view",
        "fertigation.plan.view",
        "fertilizer.view",
        "weather.view",
        "vision.camera.view",
        "vision.model.view",
        "vision.detection.view",
        "crophealth.disease.view",
        "crophealth.incident.view",
        "crophealth.treatment.view",
        "harvest.observation.view",
        "harvest.yield.view",
        "harvest.lot.view",
        "notification.view",
    ],
}
