"""Permission catalog and default role grants.

Permissions are `module.feature.action` strings (per the platform brief's
§34 shape) stored as data in the `permissions` table, not a code enum - new
modules add rows here as they land in later phases (FR-PLT-009: master data
is shared platform config, not per-feature hardcoding). Roles mirror the
persona list in 01-VISION.md §4.
"""

PERMISSIONS: list[tuple[str, str]] = [
    ("platform.tenant.create", "Create a new tenant (platform super admin only in practice)"),
    ("platform.user.manage", "Create/update users within the tenant"),
    ("platform.role.assign", "Assign roles/scopes to users"),
    ("platform.audit.view", "View the audit trail"),
    ("platform.config.manage", "Read/write tenant configuration"),
    ("master_data.crop.view", "View crop/variety master data"),
    ("master_data.crop.manage", "Create/update crop/variety master data"),
    ("farm.view", "View farm/zone/plot/block/row hierarchy"),
    ("farm.manage", "Create/update farm/zone/plot/block/row hierarchy"),
    ("tree.view", "View tree twins and their history"),
    ("tree.manage", "Create/update/delete tree twins"),
    ("tree.event.record", "Record a tree history event (health/irrigation/treatment/harvest/...)"),
    ("season.view", "View seasons"),
    ("season.manage", "Create/update seasons"),
    ("twin.view", "View digital twins, their properties, events, and telemetry"),
    ("twin.manage", "Create/update/delete digital twins, their relationships, properties, and events"),
    ("twin.telemetry.write", "Record telemetry readings against a digital twin"),
    ("iot.device.view", "View IoT device/gateway registrations"),
    ("iot.device.manage", "Register/update IoT devices and gateways"),
    ("iot.rule.view", "View IoT threshold rules"),
    ("iot.rule.manage", "Create/update IoT threshold rules"),
    ("alert.view", "View alerts"),
    ("alert.manage", "Acknowledge/resolve alerts"),
    ("irrigation.plan.view", "View irrigation plans and events"),
    ("irrigation.plan.manage", "Create/submit/execute irrigation plans"),
    ("fertigation.plan.view", "View fertigation plans and events"),
    ("fertigation.plan.manage", "Create/submit/execute fertigation plans"),
    ("fertilizer.view", "View fertilizer master data"),
    ("fertilizer.manage", "Create/update fertilizer master data"),
    ("weather.view", "View weather readings"),
    ("weather.ingest", "Ingest station/forecast weather readings"),
    ("vision.camera.view", "View camera registrations"),
    ("vision.camera.manage", "Register/update cameras"),
    ("vision.model.view", "View the vision model catalog"),
    ("vision.model.manage", "Create/update vision model catalog entries"),
    ("vision.detection.view", "View vision AI detections"),
    ("vision.detection.manage", "Create detections and confirm/reject them"),
    ("crophealth.disease.view", "View the disease/pest master catalog"),
    ("crophealth.disease.manage", "Create/update the disease/pest master catalog"),
    ("crophealth.incident.view", "View disease incidents and disease-risk signals"),
    ("crophealth.incident.manage", "Create disease incidents and change their lifecycle status"),
    ("crophealth.treatment.view", "View treatment plans and events"),
    ("crophealth.treatment.manage", "Create/submit/execute treatment plans"),
    ("harvest.observation.view", "View fruit lifecycle observations"),
    ("harvest.observation.manage", "Record fruit lifecycle observations"),
    ("harvest.yield.view", "View yield forecasts"),
    ("harvest.yield.manage", "Create yield forecasts"),
    ("harvest.lot.view", "View harvest lots and packing lots"),
    ("harvest.lot.manage", "Create harvest lots and packing lots"),
    ("asset.view", "View assets (asset-category digital twins)"),
    ("asset.manage", "Register/update assets"),
    ("asset.assess", "Run a predictive-maintenance health assessment against an asset"),
    ("asset.maintenance.view", "View maintenance requests and work orders"),
    ("asset.maintenance.manage", "Create/submit maintenance requests, convert to and update work orders"),
    ("inventory.item.view", "View the inventory item master"),
    ("inventory.item.manage", "Create/update inventory items"),
    ("inventory.warehouse.view", "View warehouses"),
    ("inventory.warehouse.manage", "Create/update warehouses"),
    ("inventory.vendor.view", "View the vendor master"),
    ("inventory.vendor.manage", "Create/update vendors"),
    ("inventory.stock.view", "View stock lots and movements"),
    ("inventory.stock.manage", "Receive stock and record stock movements"),
    ("procurement.request.view", "View purchase requests"),
    ("procurement.request.manage", "Create/submit purchase requests"),
    ("procurement.order.view", "View purchase orders"),
    ("procurement.order.manage", "Issue, receive, and invoice-match purchase orders"),
    ("accounting.costcenter.view", "View cost centers"),
    ("accounting.costcenter.manage", "Create/update cost centers"),
    ("accounting.ledger.view", "View ledger entries and profitability"),
    ("accounting.ledger.manage", "Post ledger entries"),
    ("accounting.budget.view", "View budgets and variance"),
    ("accounting.budget.manage", "Create budgets"),
    ("sales.customer.view", "View the customer master"),
    ("sales.customer.manage", "Create/update customers"),
    ("sales.order.view", "View sales orders, invoices, and payments"),
    ("sales.order.manage", "Create/confirm/deliver sales orders, issue invoices, record payments"),
    ("workflow.definition.manage", "Create/update approval workflow definitions"),
    ("workflow.instance.submit", "Submit an entity for approval"),
    ("workflow.instance.approve", "Approve/reject/return a submitted workflow instance"),
    ("notification.view", "View own notifications"),
    ("ai.model.view", "View the AI model registry"),
    ("ai.model.manage", "Register/update AI models and versions"),
    ("ai.prediction.view", "View recorded predictions"),
    ("ai.prediction.manage", "Submit feedback on predictions"),
    ("ai.agent.propose", "Propose and view agent actions"),
    ("ai.agent.approve", "Submit and approve/reject L3 agent actions"),
    ("ai.agent.execute", "Execute an approved or supervised agent action"),
    ("ai.agent.policy.manage", "Grant/revoke L4 autonomous-execution policy grants"),
    ("ai.copilot.use", "Ask the AI Copilot questions"),
    ("dashboard.view", "View the Command Center fleet and per-farm summary rollups"),
    ("work.task.view", "View work tasks"),
    ("work.task.manage", "Request/plan/assign/cancel work tasks"),
    ("work.task.execute", "Accept/reject/start/complete work tasks assigned to you"),
    ("work.task.review", "Review a completed work task and close it or send it back"),
]

SYSTEM_ROLES: list[tuple[str, str]] = [
    ("tenant_admin", "Tenant Admin"),
    ("farm_owner", "Farm Owner"),
    ("farm_manager", "Farm Manager"),
    ("agronomist", "Agronomist"),
    ("field_worker", "Field Worker"),
    ("maintenance_engineer", "Maintenance Engineer"),
    ("warehouse_officer", "Warehouse / Procurement Officer"),
    ("finance", "Finance / Cost Controller"),
    ("auditor", "Auditor"),
    ("viewer", "Viewer"),
]

DEFAULT_ROLE_PERMISSIONS: dict[str, list[str]] = {
    "tenant_admin": [code for code, _ in PERMISSIONS],
    "farm_owner": [
        "platform.audit.view",
        "master_data.crop.view",
        "farm.view",
        "farm.manage",
        "tree.view",
        "tree.manage",
        "season.view",
        "season.manage",
        "twin.view",
        "twin.manage",
        "iot.device.view",
        "iot.device.manage",
        "iot.rule.view",
        "iot.rule.manage",
        "alert.view",
        "alert.manage",
        "irrigation.plan.view",
        "irrigation.plan.manage",
        "fertigation.plan.view",
        "fertigation.plan.manage",
        "fertilizer.view",
        "fertilizer.manage",
        "weather.view",
        "weather.ingest",
        "vision.camera.view",
        "vision.camera.manage",
        "vision.model.view",
        "vision.model.manage",
        "vision.detection.view",
        "vision.detection.manage",
        "crophealth.disease.view",
        "crophealth.disease.manage",
        "crophealth.incident.view",
        "crophealth.incident.manage",
        "crophealth.treatment.view",
        "crophealth.treatment.manage",
        "harvest.observation.view",
        "harvest.observation.manage",
        "harvest.yield.view",
        "harvest.yield.manage",
        "harvest.lot.view",
        "harvest.lot.manage",
        "asset.view",
        "asset.manage",
        "asset.assess",
        "asset.maintenance.view",
        "asset.maintenance.manage",
        "inventory.item.view",
        "inventory.item.manage",
        "inventory.warehouse.view",
        "inventory.warehouse.manage",
        "inventory.vendor.view",
        "inventory.vendor.manage",
        "inventory.stock.view",
        "inventory.stock.manage",
        "procurement.request.view",
        "procurement.request.manage",
        "procurement.order.view",
        "procurement.order.manage",
        "accounting.costcenter.view",
        "accounting.costcenter.manage",
        "accounting.ledger.view",
        "accounting.ledger.manage",
        "accounting.budget.view",
        "accounting.budget.manage",
        "sales.customer.view",
        "sales.customer.manage",
        "sales.order.view",
        "sales.order.manage",
        "workflow.instance.approve",
        "notification.view",
        "ai.model.view",
        "ai.prediction.view",
        "ai.prediction.manage",
        "ai.agent.propose",
        "ai.agent.approve",
        "ai.agent.execute",
        "ai.copilot.use",
        "dashboard.view",
        "work.task.view",
        "work.task.manage",
        "work.task.execute",
        "work.task.review",
    ],
    "farm_manager": [
        "master_data.crop.view",
        "farm.view",
        "farm.manage",
        "tree.view",
        "tree.manage",
        "tree.event.record",
        "season.view",
        "season.manage",
        "twin.view",
        "twin.manage",
        "twin.telemetry.write",
        "iot.device.view",
        "iot.device.manage",
        "iot.rule.view",
        "iot.rule.manage",
        "alert.view",
        "alert.manage",
        "irrigation.plan.view",
        "irrigation.plan.manage",
        "fertigation.plan.view",
        "fertigation.plan.manage",
        "fertilizer.view",
        "fertilizer.manage",
        "weather.view",
        "weather.ingest",
        "vision.camera.view",
        "vision.camera.manage",
        "vision.model.view",
        "vision.model.manage",
        "vision.detection.view",
        "vision.detection.manage",
        "crophealth.disease.view",
        "crophealth.disease.manage",
        "crophealth.incident.view",
        "crophealth.incident.manage",
        "crophealth.treatment.view",
        "crophealth.treatment.manage",
        "harvest.observation.view",
        "harvest.observation.manage",
        "harvest.yield.view",
        "harvest.yield.manage",
        "harvest.lot.view",
        "harvest.lot.manage",
        "asset.view",
        "asset.manage",
        "asset.assess",
        "asset.maintenance.view",
        "asset.maintenance.manage",
        "inventory.item.view",
        "inventory.item.manage",
        "inventory.warehouse.view",
        "inventory.warehouse.manage",
        "inventory.vendor.view",
        "inventory.vendor.manage",
        "inventory.stock.view",
        "inventory.stock.manage",
        "procurement.request.view",
        "procurement.request.manage",
        "procurement.order.view",
        "procurement.order.manage",
        "accounting.costcenter.view",
        "accounting.costcenter.manage",
        "accounting.ledger.view",
        "accounting.ledger.manage",
        "accounting.budget.view",
        "accounting.budget.manage",
        "sales.customer.view",
        "sales.customer.manage",
        "sales.order.view",
        "sales.order.manage",
        "workflow.instance.submit",
        "workflow.instance.approve",
        "notification.view",
        "ai.model.view",
        "ai.prediction.view",
        "ai.prediction.manage",
        "ai.agent.propose",
        "ai.agent.approve",
        "ai.agent.execute",
        "ai.copilot.use",
        "dashboard.view",
        "work.task.view",
        "work.task.manage",
        "work.task.execute",
        "work.task.review",
    ],
    "agronomist": [
        "master_data.crop.view",
        "farm.view",
        "tree.view",
        "tree.manage",
        "tree.event.record",
        "season.view",
        "twin.view",
        "iot.device.view",
        "iot.rule.view",
        "alert.view",
        "irrigation.plan.view",
        "irrigation.plan.manage",
        "fertigation.plan.view",
        "fertigation.plan.manage",
        "fertilizer.view",
        "weather.view",
        "vision.camera.view",
        "vision.model.view",
        "vision.detection.view",
        "vision.detection.manage",
        "crophealth.disease.view",
        "crophealth.incident.view",
        "crophealth.incident.manage",
        "crophealth.treatment.view",
        "crophealth.treatment.manage",
        "harvest.observation.view",
        "harvest.observation.manage",
        "harvest.yield.view",
        "harvest.yield.manage",
        "harvest.lot.view",
        "harvest.lot.manage",
        "asset.view",
        "inventory.item.view",
        "inventory.stock.view",
        "workflow.instance.submit",
        "notification.view",
        "ai.model.view",
        "ai.prediction.view",
        "ai.prediction.manage",
        "ai.agent.propose",
        "ai.copilot.use",
        "dashboard.view",
        "work.task.view",
        "work.task.manage",
        "work.task.execute",
    ],
    "field_worker": [
        "farm.view",
        "tree.view",
        "tree.event.record",
        "twin.view",
        "iot.device.view",
        "alert.view",
        "alert.manage",
        "irrigation.plan.view",
        "irrigation.plan.manage",
        "fertigation.plan.view",
        "fertigation.plan.manage",
        "fertilizer.view",
        "weather.view",
        "weather.ingest",
        "vision.camera.view",
        "vision.detection.view",
        "vision.detection.manage",
        "crophealth.disease.view",
        "crophealth.incident.view",
        "crophealth.treatment.view",
        "crophealth.treatment.manage",
        "harvest.observation.view",
        "harvest.observation.manage",
        "harvest.yield.view",
        "harvest.lot.view",
        "harvest.lot.manage",
        "asset.view",
        "asset.maintenance.view",
        "asset.maintenance.manage",
        "inventory.item.view",
        "inventory.stock.view",
        "inventory.stock.manage",
        "notification.view",
        "ai.model.view",
        "ai.prediction.view",
        "ai.agent.propose",
        "ai.copilot.use",
        "dashboard.view",
        "work.task.view",
        "work.task.execute",
    ],
    "maintenance_engineer": [
        "twin.view",
        "twin.manage",
        "twin.telemetry.write",
        "iot.device.view",
        "iot.device.manage",
        "iot.rule.view",
        "iot.rule.manage",
        "alert.view",
        "alert.manage",
        "asset.view",
        "asset.manage",
        "asset.assess",
        "asset.maintenance.view",
        "asset.maintenance.manage",
        "inventory.item.view",
        "inventory.stock.view",
        "inventory.stock.manage",
        "workflow.instance.submit",
        "notification.view",
        "ai.model.view",
        "ai.prediction.view",
        "ai.prediction.manage",
        "ai.agent.propose",
        "ai.copilot.use",
        "dashboard.view",
        "work.task.view",
        "work.task.execute",
    ],
    "warehouse_officer": [
        "inventory.item.view",
        "inventory.item.manage",
        "inventory.warehouse.view",
        "inventory.warehouse.manage",
        "inventory.vendor.view",
        "inventory.vendor.manage",
        "inventory.stock.view",
        "inventory.stock.manage",
        "procurement.request.view",
        "procurement.request.manage",
        "procurement.order.view",
        "procurement.order.manage",
        "asset.view",
        "workflow.instance.submit",
        "notification.view",
        "ai.model.view",
        "ai.prediction.view",
        "ai.agent.propose",
        "ai.copilot.use",
        "dashboard.view",
        "work.task.view",
    ],
    "finance": [
        "workflow.instance.approve",
        "platform.audit.view",
        "accounting.costcenter.view",
        "accounting.costcenter.manage",
        "accounting.ledger.view",
        "accounting.ledger.manage",
        "accounting.budget.view",
        "accounting.budget.manage",
        "sales.customer.view",
        "sales.customer.manage",
        "sales.order.view",
        "sales.order.manage",
        "procurement.request.view",
        "procurement.order.view",
        "inventory.item.view",
        "inventory.stock.view",
        "notification.view",
        "ai.model.view",
        "ai.prediction.view",
        "ai.copilot.use",
        "dashboard.view",
        "work.task.view",
    ],
    "auditor": ["platform.audit.view", "notification.view", "ai.model.view", "ai.prediction.view", "dashboard.view", "work.task.view"],
    "viewer": [
        "master_data.crop.view",
        "farm.view",
        "tree.view",
        "season.view",
        "twin.view",
        "iot.device.view",
        "iot.rule.view",
        "alert.view",
        "irrigation.plan.view",
        "fertigation.plan.view",
        "fertilizer.view",
        "weather.view",
        "vision.camera.view",
        "vision.model.view",
        "vision.detection.view",
        "crophealth.disease.view",
        "crophealth.incident.view",
        "crophealth.treatment.view",
        "harvest.observation.view",
        "harvest.yield.view",
        "harvest.lot.view",
        "asset.view",
        "asset.maintenance.view",
        "inventory.item.view",
        "inventory.warehouse.view",
        "inventory.vendor.view",
        "inventory.stock.view",
        "procurement.request.view",
        "procurement.order.view",
        "accounting.costcenter.view",
        "accounting.ledger.view",
        "accounting.budget.view",
        "sales.customer.view",
        "sales.order.view",
        "notification.view",
        "ai.model.view",
        "ai.prediction.view",
        "ai.copilot.use",
        "dashboard.view",
        "work.task.view",
    ],
}
